version: '3'
services:
  sniffer:
    build: ./sniffer
    networks:
      - sniffer_network
    depends_on:
      - kafka
      - db
    environment:
      - KAFKA_SERVER=kafka:9092
      - DB_HOST=db
    volumes:
      - ./sniffer:/app

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_INTERNAL: INSIDE://kafka:9093
      KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - sniffer_network

  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - sniffer_network

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: network_db
    networks:
      - sniffer_network

  web:
    build:
      context: ./web
    ports:
      - "5000:5000"
    networks:
      - sniffer_network
    depends_on:
      - sniffer

networks:
  sniffer_network:
    driver: bridge
